import type { Question } from '@/types'

/**
 * The question bank. Each domain climbs the same ladder:
 *   1 경험 → 2 정의 → 3 대조 → 4 종합
 * so that a reader always starts from lived experience, then defines terms,
 * then meets other positions, and only then states their own.
 *
 * Writing conventions:
 *  - Prefer “무엇/어떻게” over “왜” (Eurich; Kross): 왜-질문은 반추로 흐르기 쉽다.
 *  - Ask for one concrete scene before any abstraction.
 *  - Every level-4 question demands both a position and what it excludes.
 */
export const QUESTIONS: Question[] = [
  // ───────────────────────────── 행복 ─────────────────────────────
  {
    id: 'hap-moments',
    domainId: 'happiness',
    level: 1,
    kind: 'experience',
    title: '최근 한 달 중 ‘행복했다’고 느낀 순간 세 장면을 구체적으로 적어보세요.',
    why: '행복을 정의하기 전에 사례부터 모아야 합니다. 세 장면의 공통점이 곧 당신의 행복 이론의 첫 가설입니다.',
    cues: [
      '언제, 어디서, 누구와, 무엇을 하던 중이었나요?',
      '그 순간 몸의 감각은 어땠나요? (가벼움, 따뜻함, 느려짐…)',
      '그 순간이 끝난 직후 무엇을 했나요?',
      '세 장면에서 반복되는 요소 하나를 찾아 밑줄 치세요.',
    ],
    lensIds: ['kahneman-two-selves', 'suh-origin-of-happiness', 'killingsworth-wandering-mind'],
    tags: ['행복', '경험', '순간', '기억'],
    minutes: 10,
  },
  {
    id: 'hap-unhappy',
    domainId: 'happiness',
    level: 1,
    kind: 'experience',
    title: '반대로 분명히 불행했던 순간은 언제였고, 그때 무엇이 빠져 있었나요?',
    why: '결핍은 필요를 드러냅니다. 불행의 순간에 부재했던 것이 당신에게 행복의 필요조건일 가능성이 큽니다.',
    cues: [
      '장면 하나를 고르고, 사실만 먼저 적으세요.',
      '그때 없었던 것: 사람, 자율, 유능감, 안전, 휴식, 의미… 무엇이었나요?',
      '같은 상황에서 불행하지 않았을 사람이 있다면, 무엇이 달랐을까요?',
    ],
    caution: '괴로운 기억이라면 3인칭으로(이름을 써서) 서술해보세요. 압도되면 멈추어도 됩니다.',
    lensIds: ['sdt-needs', 'schopenhauer-pendulum', 'buddhism-dukkha'],
    tags: ['행복', '불행', '결핍', '경험'],
    minutes: 10,
  },
  {
    id: 'hap-expect-vs-actual',
    domainId: 'happiness',
    level: 1,
    kind: 'experience',
    title: '행복할 거라 기대했는데 막상 그렇지 않았던 일, 기대하지 않았는데 행복했던 일을 하나씩 적어보세요.',
    why: '우리는 미래의 감정을 체계적으로 잘못 예측합니다. 예측이 빗나간 지점이 당신의 행복 모델이 틀린 지점입니다.',
    cues: [
      '기대가 빗나간 일: 취업, 구매, 여행, 관계… 기대와 실제의 차이를 적으세요.',
      '기대 없이 행복했던 일: 그 행복은 얼마나 오래갔나요?',
      '두 사례에서 배울 수 있는 ‘예측 규칙’ 하나를 만들어보세요.',
    ],
    lensIds: ['gilbert-affective-forecasting', 'hedonic-adaptation', 'kahneman-two-selves'],
    tags: ['행복', '기대', '예측', '적응'],
    minutes: 10,
  },
  {
    id: 'hap-define',
    domainId: 'happiness',
    level: 2,
    kind: 'definition',
    title: '당신이 쓰는 ‘행복’이라는 말은 무엇을 가리키나요? 쾌락, 만족, 의미, 평온, 풍요로움 중 어디에 가까운가요?',
    why: '같은 단어로 다른 것을 가리키면 논의가 겉돕니다. 행복이 ‘좋은 느낌’인지 ‘좋은 삶’인지부터 정해야 다음 질문들이 풀립니다.',
    cues: [
      '다섯 후보 각각에 대해 ‘이것이 없어도 행복이라 부를 수 있는가’를 물어보세요.',
      '하루 단위의 행복과 인생 단위의 행복은 같은 것인가요?',
      '당신의 정의로 보면 ‘행복하지만 잘못 사는 사람’이 가능한가요?',
    ],
    prereqIds: ['hap-moments'],
    lensIds: ['parfit-wellbeing-theories', 'aristotle-eudaimonia', 'epicurus-ataraxia', 'oishi-psychological-richness'],
    tags: ['행복', '정의', '쾌락', '만족', '에우다이모니아'],
    minutes: 15,
  },
  {
    id: 'hap-happy-vs-meaningful',
    domainId: 'happiness',
    level: 2,
    kind: 'definition',
    title: '행복한 삶과 의미 있는 삶이 갈라진다면 어느 쪽을 택하겠습니까? 둘은 당신에게 어떻게 다른가요?',
    why: '연구는 행복과 의미가 겹치지만 다른 것이라고 말합니다. 주는 것, 과거·미래를 생각하는 것, 스트레스는 의미와 붙어 있고 행복과는 멀어질 수 있습니다.',
    cues: [
      '행복하지만 의미가 얕았던 시기, 의미 있지만 행복하지 않았던 시기를 각각 떠올려보세요.',
      '지금 당신은 어느 쪽으로 기울어 있나요? 그것은 선택인가요, 상황인가요?',
      '둘 다 가질 수 없다면 무엇을 포기하겠습니까?',
    ],
    lensIds: ['baumeister-happy-vs-meaningful', 'susan-wolf-meaning', 'frankl-logotherapy'],
    tags: ['행복', '의미', '대조'],
    minutes: 15,
  },
  {
    id: 'hap-conditions',
    domainId: 'happiness',
    level: 2,
    kind: 'definition',
    title: '행복의 조건이라 믿는 것들을 적고, 각각이 ‘필요조건’인지 ‘있으면 좋은 것’인지 구분해보세요.',
    why: '조건 목록을 만들면 지금 무엇을 쫓고 있는지, 그것이 정말 필요한지가 보입니다. 돈·관계·건강·자율에 대한 연구 결과와 비교해보세요.',
    cues: [
      '떠오르는 조건을 모두 적은 뒤, ‘이것 없이 행복한 사람을 아는가’로 걸러보세요.',
      '돈은 어디까지 필요조건인가요? 그 선을 숫자로 적어보세요.',
      '지금 가장 부족한 조건과 가장 과잉인 조건은?',
    ],
    lensIds: ['sdt-needs', 'harvard-adult-development', 'income-and-happiness', 'ryff-pwb'],
    tags: ['행복', '조건', '돈', '관계', '건강'],
    minutes: 15,
  },
  {
    id: 'hap-experience-machine',
    domainId: 'happiness',
    level: 3,
    kind: 'thought-experiment',
    title: '원하는 모든 경험을 완벽하게 시뮬레이션해주는 기계가 있다면, 평생 접속하겠습니까?',
    why: '노직의 경험 기계는 ‘행복은 결국 좋은 느낌인가’를 시험합니다. 접속을 거부한다면 당신은 느낌 이상의 무언가를 원하는 것입니다.',
    cues: [
      '즉답을 적은 뒤, 거부/수락의 이유를 세 가지 이상 적어보세요.',
      '거부했다면: 느낌 말고 무엇이 중요한가요? (실제로 함, 실제 사람, 진실…)',
      '수락했다면: 지금의 삶에서 무엇이 ‘가짜여도 상관없는’ 것인가요?',
    ],
    prereqIds: ['hap-define'],
    lensIds: ['nozick-experience-machine', 'parfit-wellbeing-theories', 'mill-utilitarianism'],
    tags: ['행복', '사고실험', '쾌락주의', '진실'],
    minutes: 15,
  },
  {
    id: 'hap-pursuit-paradox',
    domainId: 'happiness',
    level: 3,
    kind: 'contrast',
    title: '행복을 직접 목표로 삼는 것이 오히려 행복을 해친다는 주장에 대해 어떻게 생각하나요?',
    why: '밀은 ‘행복한지 자문하는 순간 행복은 사라진다’고 썼고, 심리학 실험은 행복을 지나치게 중시하는 사람이 덜 행복하다고 보고합니다. 행복은 목표인가, 부산물인가?',
    cues: [
      '행복해지려고 애쓸수록 멀어졌던 경험이 있나요?',
      '행복이 부산물이라면 무엇의 부산물인가요? 그것을 목표로 삼을 수는 있나요?',
      '이 주장이 틀린 경우(행복을 챙겨서 좋아진 경우)도 적어보세요.',
    ],
    lensIds: ['mauss-valuing-happiness-paradox', 'mill-utilitarianism', 'frankl-logotherapy', 'csikszentmihalyi-flow'],
    tags: ['행복', '역설', '추구', '몰입'],
    minutes: 15,
  },
  {
    id: 'hap-culture',
    domainId: 'happiness',
    level: 3,
    kind: 'contrast',
    title: '당신의 행복관 중 어디까지가 ‘나의 것’이고, 어디부터가 한국 사회·가족·SNS가 심어준 것인가요?',
    why: '동아시아와 서구의 행복 개념은 다릅니다(관계 속 조화 vs 개인의 성취). 비교와 성과 압력이 큰 사회에서 행복관은 쉽게 외부에서 주입됩니다.',
    cues: [
      '‘행복하려면 ___해야 한다’는 문장을 다섯 개 적고, 출처(부모, 학교, 미디어, 나)를 표시하세요.',
      '남과 비교하지 않는다면 지금의 삶은 몇 점인가요?',
      '문화가 준 행복관 중 지키고 싶은 것 하나, 돌려주고 싶은 것 하나는?',
    ],
    lensIds: ['uchida-east-west-happiness', 'markus-kitayama-self', 'han-burnout-society', 'suh-origin-of-happiness'],
    tags: ['행복', '문화', '한국', '비교', '사회'],
    minutes: 15,
  },
  {
    id: 'hap-stoic-test',
    domainId: 'happiness',
    level: 3,
    kind: 'contrast',
    title: '행복이 외부 조건과 무관하게 가능하다는 스토아·불교의 주장을 당신의 삶에서 시험해본다면?',
    why: '가장 급진적인 행복론은 ‘조건을 바꾸지 말고 조건에 대한 판단을 바꾸라’고 말합니다. 어디까지 동의할 수 있는지가 당신의 입장을 선명하게 합니다.',
    cues: [
      '지금 행복을 막는다고 느끼는 조건 하나를 고르세요. 그 조건에 대한 판단을 바꿀 수 있나요?',
      '판단을 바꾸는 것이 지혜인 경우와 체념인 경우의 차이는?',
      '완전히 내적인 행복이 가능하다면, 왜 우리는 여전히 조건을 바꾸려 하나요?',
    ],
    lensIds: ['stoicism-dichotomy', 'buddhism-dukkha', 'epicurus-ataraxia'],
    tags: ['행복', '스토아', '불교', '통제', '수용'],
    minutes: 15,
  },
  {
    id: 'hap-synthesis',
    domainId: 'happiness',
    level: 4,
    kind: 'synthesis',
    title: '지금까지의 답을 바탕으로 ‘행복이란 ___이다’를 당신의 말로 완성하고, 그 정의가 배제하는 것을 명시하세요.',
    why: '정의는 포함만큼 배제로 완성됩니다. 무엇을 행복이라 부르지 않기로 했는지가 당신의 철학을 분명하게 만듭니다.',
    cues: [
      '한 문장 정의 → 그 정의에 들어맞는 당신의 경험 두 개 → 들어맞지 않는 경험 하나.',
      '이 정의를 따르면 앞으로 무엇을 덜 하고 무엇을 더 하게 되나요?',
      '가장 강한 반론(다른 관점)을 적고, 그럼에도 이 정의를 택하는 이유를 쓰세요.',
    ],
    prereqIds: ['hap-define', 'hap-moments'],
    lensIds: ['aristotle-eudaimonia', 'parfit-wellbeing-theories', 'seligman-perma', 'choi-good-life'],
    tags: ['행복', '종합', '정의', '입장'],
    minutes: 20,
  },

  // ───────────────────────────── 의미와 목적 ─────────────────────────────
  {
    id: 'mean-felt',
    domainId: 'meaning',
    level: 1,
    kind: 'experience',
    title: '최근에 ‘이 일은 의미 있다’고 느낀 순간과 ‘이게 다 무슨 소용인가’ 싶었던 순간을 하나씩 적어보세요.',
    why: '의미는 거창한 사명보다 일상의 순간에서 먼저 감지됩니다. 두 순간을 나란히 놓으면 당신에게 의미를 주는 요소가 드러납니다.',
    cues: [
      '의미 있던 순간: 누구를 위한 일이었나요? 무엇이 이어지고 있었나요?',
      '허무했던 순간: 무엇이 끊겨 있었나요? (연결, 이유, 결과, 인정…)',
      '두 순간의 차이를 한 단어로 표현한다면?',
    ],
    lensIds: ['heintzelman-king-meaning', 'frankl-logotherapy', 'tolstoy'],
    tags: ['의미', '경험', '허무', '일상'],
    minutes: 10,
  },
  {
    id: 'mean-story-ask',
    domainId: 'meaning',
    level: 1,
    kind: 'experience',
    title: '삶이 당신에게 무엇을 요구하고 있다고 느끼나요? (당신이 삶에 바라는 것이 아니라)',
    why: '프랭클은 질문의 방향을 뒤집으라고 말합니다. ‘삶에서 무엇을 얻을까’가 아니라 ‘삶이 나에게 무엇을 묻고 있나’. 이 전환만으로 의미의 감각이 달라집니다.',
    cues: [
      '지금 당신 앞에 놓인 사람, 일, 상황이 당신에게 요구하는 것은?',
      '당신만이 할 수 있는(또는 당신이 아니면 안 되는) 일이 있나요?',
      '그 요구에 응답하지 않을 때 무엇이 사라지나요?',
    ],
    lensIds: ['frankl-logotherapy', 'arendt-vita-activa', 'murdoch-attention'],
    tags: ['의미', '책임', '응답', '소명'],
    minutes: 10,
  },
  {
    id: 'mean-three',
    domainId: 'meaning',
    level: 2,
    kind: 'definition',
    title: '의미를 ‘이해됨(일관성)·방향(목적)·중요함(가치)’으로 나눈다면, 지금 각각은 어느 정도인가요?',
    why: '‘삶의 의미’는 하나의 질문이 아니라 세 개의 질문입니다. 내 삶이 이해되는가, 어디로 가는가, 그것이 중요한가. 셋을 따로 점검하면 막연함이 걷힙니다.',
    cues: [
      '일관성: 지금까지의 삶이 하나의 이야기로 이해되나요? (0–10)',
      '목적: 앞으로 향하는 방향이 있나요? 그 방향은 누가 정했나요? (0–10)',
      '중요성: 당신의 삶이 누군가/무언가에게 중요한가요? (0–10)',
      '가장 낮은 것은 무엇이고, 그것을 높이려면 어떤 질문에 답해야 할까요?',
    ],
    lensIds: ['martela-steger-three-meanings', 'steger-mlq', 'heintzelman-king-meaning'],
    tags: ['의미', '일관성', '목적', '중요성', '점검'],
    minutes: 15,
  },
  {
    id: 'mean-purpose-vs-meaning',
    domainId: 'meaning',
    level: 2,
    kind: 'definition',
    title: '‘삶의 목적’과 ‘삶의 의미’는 같은 말인가요? 목적 없이도 의미 있는 삶이 가능한가요?',
    why: '목적은 ‘완수할 수 있는 것(telic)’이고, 의미는 ‘하는 중에 있는 것(atelic)’일 수 있습니다. 둘을 구분하면 ‘목표를 이뤘는데 허무한’ 역설이 설명됩니다.',
    cues: [
      '당신이 이룬 목적 중 이루고 나서 허무했던 것은?',
      '끝이 없어도 계속하고 싶은 활동(걷기, 배우기, 돌보기)은 무엇인가요?',
      '‘목적 없는 삶’이라는 말이 두렵다면, 그 두려움은 무엇에 대한 것인가요?',
    ],
    lensIds: ['setiya-telic-atelic', 'zhuangzi-useless-tree', 'susan-wolf-meaning'],
    tags: ['의미', '목적', '텔릭', '아텔릭'],
    minutes: 15,
  },
  {
    id: 'mean-source',
    domainId: 'meaning',
    level: 2,
    kind: 'definition',
    title: '당신의 의미는 어디서 오나요? 창조(일), 만남(사랑), 태도(고통) — 프랭클의 세 통로로 분류해보세요.',
    why: '의미의 출처를 알면 위기 때 어디로 돌아가야 하는지 압니다. 세 통로 중 한 곳에만 기대고 있다면 그 통로가 막혔을 때 취약해집니다.',
    cues: [
      '만들어낸 것(작품, 결과, 조직)에서 오는 의미는?',
      '누군가를 만나고 사랑하는 데서 오는 의미는?',
      '바꿀 수 없는 고통을 대하는 태도에서 오는 의미는?',
      '셋 중 가장 비어 있는 통로는?',
    ],
    lensIds: ['frankl-logotherapy', 'ikigai-kamiya', 'williams-ground-projects'],
    tags: ['의미', '출처', '일', '사랑', '고통'],
    minutes: 15,
  },
  {
    id: 'mean-absurd',
    domainId: 'meaning',
    level: 3,
    kind: 'thought-experiment',
    title: '우주적 관점에서 보면 당신의 삶은 아무 의미가 없다는 주장에 어떻게 답하겠습니까?',
    why: '허무의 논증을 정면으로 통과하지 않은 의미는 첫 위기에 무너집니다. 카뮈의 반항, 네이글의 아이러니, 톨스토이의 회심 중 당신의 응답은 무엇인가요?',
    cues: [
      '이 주장이 옳다고 가정하고 하루를 산다면 실제로 무엇이 달라지나요?',
      '‘의미 있으려면 영원해야/거대해야 한다’는 전제가 이 주장 안에 숨어 있나요?',
      '당신의 응답: 반항, 아이러니, 신앙, 무시, 수용 중 무엇에 가깝나요?',
    ],
    prereqIds: ['mean-three'],
    lensIds: ['camus-absurd', 'nagel-absurd', 'tolstoy'],
    tags: ['의미', '허무', '부조리', '사고실험'],
    minutes: 20,
  },
  {
    id: 'mean-given-vs-made',
    domainId: 'meaning',
    level: 3,
    kind: 'contrast',
    title: '의미는 ‘발견’되는 것인가, ‘발명’되는 것인가? 당신은 어느 쪽에 서 있고, 그 입장의 약점은 무엇인가요?',
    why: '사르트르는 우리가 의미를 만든다고, 프랭클은 의미가 우리를 기다린다고 말합니다. 어느 쪽이든 약점이 있습니다: 발명은 자의적일 수 있고, 발견은 근거를 요구합니다.',
    cues: [
      '당신이 ‘만든’ 의미와 ‘주어진’ 의미를 하나씩 적어보세요.',
      '발명한 의미가 흔들릴 때 무엇이 그것을 지탱하나요?',
      '수전 울프처럼 ‘내가 끌리는 것 + 실제로 가치 있는 것’의 만남으로 본다면?',
    ],
    lensIds: ['sartre-existentialism', 'frankl-logotherapy', 'taylor-authenticity', 'susan-wolf-meaning'],
    tags: ['의미', '실존주의', '발견', '발명', '진정성'],
    minutes: 20,
  },
  {
    id: 'mean-sisyphus',
    domainId: 'meaning',
    level: 3,
    kind: 'contrast',
    title: '당신의 시지프 바위는 무엇인가요? 그것을 굴리는 일을 긍정할 수 있나요?',
    why: '반복되는 일(출근, 설거지, 돌봄)을 어떻게 대하느냐가 실제 삶의 대부분을 결정합니다. 카뮈는 ‘행복한 시지프를 상상해야 한다’고 썼습니다.',
    cues: [
      '끝없이 반복되는 당신의 일 하나를 고르세요.',
      '그 일이 의미 있는 조건(누구를 위해, 어떤 태도로)은 무엇인가요?',
      '니체의 영원회귀: 이 일을 영원히 반복해야 한다면 긍정할 수 있나요?',
    ],
    lensIds: ['camus-absurd', 'nietzsche', 'setiya-telic-atelic'],
    tags: ['의미', '반복', '일상', '긍정', '영원회귀'],
    minutes: 15,
  },
  {
    id: 'mean-eastern',
    domainId: 'meaning',
    level: 3,
    kind: 'contrast',
    title: '‘목적’이라는 틀 자체를 내려놓는 동양적 관점(장자, 노자, 선불교)에서 당신의 삶을 다시 본다면?',
    why: '‘삶의 목적은 무엇인가’는 특정 문화의 질문 형식일 수 있습니다. 장자의 쓸모없는 나무, 노자의 무위는 목적 없이 사는 것이 결핍이 아닐 수 있음을 보여줍니다.',
    cues: [
      '쓸모(목적)를 묻지 않고 그저 존재하는 것들 중 당신이 사랑하는 것은?',
      '‘목적이 있어야 한다’는 압박이 사라지면 오늘 무엇을 다르게 하나요?',
      '이 관점의 위험(수동성, 회피)은 당신에게 얼마나 현실적인가요?',
    ],
    lensIds: ['zhuangzi-useless-tree', 'laozi-wuwei', 'buddhism-dukkha', 'wonhyo-hwajaeng'],
    tags: ['의미', '동양', '장자', '무위', '선'],
    minutes: 15,
  },
  {
    id: 'mean-synthesis',
    domainId: 'meaning',
    level: 4,
    kind: 'synthesis',
    title: '‘내 삶의 목적/의미는 ___이다’ 또는 ‘나는 목적이라는 틀 대신 ___를 택한다’를 쓰고, 어떤 반론이 가장 아프게 남는지 적으세요.',
    why: '종합은 확신이 아니라 책임입니다. 반론을 알면서도 택한 입장만이 위기에서 버팁니다.',
    cues: [
      '한 문장으로 쓴 뒤, 그것이 이번 주의 시간 배분에 어떻게 드러나는지 확인하세요.',
      '이 입장이 틀렸다면 어떤 증거가 그것을 보여줄까요?',
      '5년 뒤에도 같은 문장을 쓸 것 같나요? 바뀐다면 어느 부분이?',
    ],
    prereqIds: ['mean-three', 'mean-source'],
    lensIds: ['susan-wolf-meaning', 'frankl-logotherapy', 'camus-absurd', 'martela-steger-three-meanings'],
    tags: ['의미', '종합', '입장'],
    minutes: 20,
  },

  // ───────────────────────────── 즐거움과 몰입 ─────────────────────────────
  {
    id: 'joy-lost-time',
    domainId: 'joy',
    level: 1,
    kind: 'experience',
    title: '최근 시간 가는 줄 모르고 몰두했던 활동 세 가지는? 공통 조건(도전 수준, 혼자/함께, 즉각적 피드백)을 찾아보세요.',
    why: '몰입(flow)은 즐거움의 가장 신뢰할 만한 지표입니다. 몰입이 일어난 조건을 알면 즐거움을 ‘운’에 맡기지 않고 설계할 수 있습니다.',
    cues: [
      '활동, 소요 시간, 난이도(내 실력 대비), 피드백의 즉시성, 함께한 사람을 표로 적어보세요.',
      '세 활동의 공통점은 ‘무엇을’ 했는가보다 ‘어떻게’ 했는가에 있을 수 있습니다.',
      '몰입이 끝난 뒤의 느낌은? (충만, 허탈, 피로)',
    ],
    lensIds: ['csikszentmihalyi-flow', 'designing-your-life'],
    tags: ['즐거움', '몰입', '플로우', '경험'],
    minutes: 10,
  },
  {
    id: 'joy-energy',
    domainId: 'joy',
    level: 1,
    kind: 'experience',
    title: '하루를 되짚어 에너지를 채운 활동과 빼앗은 활동을 나눠보세요. 즐거움과 에너지는 늘 함께 가나요?',
    why: '즐거움에는 채우는 즐거움과 소모하는 즐거움이 있습니다(산책 vs 밤샘 스크롤). 에너지 축을 더하면 ‘좋아하는 것’이 두 종류로 나뉩니다.',
    cues: [
      '어제 한 일을 시간순으로 적고 각 활동 옆에 에너지(+2 ~ -2)와 즐거움(1~5)을 적어보세요.',
      '즐거웠지만 에너지를 빼앗은 활동은? 지루했지만 에너지를 채운 활동은?',
      '도구의 ‘즐거움 기록’을 일주일 써보면 패턴이 더 선명해집니다.',
    ],
    lensIds: ['designing-your-life', 'sdt-needs', 'berridge-wanting-liking'],
    tags: ['즐거움', '에너지', '기록', '습관'],
    minutes: 10,
  },
  {
    id: 'joy-childhood',
    domainId: 'joy',
    level: 1,
    kind: 'experience',
    title: '어릴 적 아무도 시키지 않았는데 계속했던 놀이는 무엇이었나요? 지금 그 흔적은 어디에 남아 있나요?',
    why: '보상도 평가도 없던 시절의 놀이는 내재적 동기의 가장 순수한 표본입니다. 그 놀이의 구조(만들기, 탐험, 경쟁, 돌보기, 수집…)는 어른이 되어도 남습니다.',
    cues: [
      '놀이 두세 개를 적고, 각각의 구조(만들기/탐험/경쟁/역할/수집/움직임)를 분류하세요.',
      '지금 하는 일이나 취미 중 같은 구조를 가진 것은?',
      '사라진 놀이가 있다면, 무엇이 그것을 멈추게 했나요?',
    ],
    lensIds: ['play-huizinga', 'intrinsic-motivation'],
    tags: ['즐거움', '놀이', '어린 시절', '내재적 동기'],
    minutes: 10,
  },
  {
    id: 'joy-wanting-vs-liking',
    domainId: 'joy',
    level: 2,
    kind: 'definition',
    title: '‘하고 싶은 것(끌림)’과 ‘실제로 하면 좋은 것(즐김)’이 어긋나는 일은? 그 둘은 왜 어긋날까요?',
    why: '뇌에서 ‘원함’과 ‘좋아함’은 다른 회로입니다. 스마트폰은 강하게 원하지만 별로 좋아하지 않을 수 있고, 운동은 원하지 않지만 하면 좋을 수 있습니다.',
    cues: [
      '원하지만 하고 나면 후회하는 것 / 원하지 않지만 하고 나면 좋은 것을 세 개씩 적으세요.',
      '어긋남의 원인: 즉시성, 습관, 광고, 사회적 비교 중 무엇이 큰가요?',
      '‘즐김’ 쪽으로 하루를 조금 옮긴다면 첫 조치는?',
    ],
    prereqIds: ['joy-energy'],
    lensIds: ['berridge-wanting-liking', 'kahneman-two-selves', 'gilbert-affective-forecasting'],
    tags: ['즐거움', '욕구', '중독', '원함', '좋아함'],
    minutes: 15,
  },
  {
    id: 'joy-kinds',
    domainId: 'joy',
    level: 2,
    kind: 'definition',
    title: '당신의 즐거움을 종류별로 나눈다면? 감각적 쾌락, 몰입, 성취, 관계, 배움, 놀이, 창작… 어디에 가장 무게가 실리나요?',
    why: '즐거움은 한 종류가 아닙니다. 분포를 알면 어떤 즐거움이 과잉이고 어떤 것이 굶주려 있는지 보입니다.',
    cues: [
      '지난 한 달의 즐거운 순간 열 개를 적고 종류를 표시하세요.',
      '가장 적게 나타난 종류는? 그것은 원래 적은 사람인가요, 지금 못 하고 있는 것인가요?',
      '스피노자의 정의로 보면, 어떤 즐거움이 당신의 ‘행위 능력’을 키우나요?',
    ],
    lensIds: ['epicurus-ataraxia', 'seligman-perma', 'oishi-psychological-richness', 'spinoza-joy'],
    tags: ['즐거움', '종류', '분류', '쾌락'],
    minutes: 15,
  },
  {
    id: 'joy-alone',
    domainId: 'joy',
    level: 2,
    kind: 'definition',
    title: '아무 자극 없이 혼자 15분을 보내는 일은 당신에게 즐거움인가요, 고역인가요? 그 답이 말해주는 것은?',
    why: '실험에서 많은 사람이 생각만 하며 앉아 있느니 전기 충격을 택했습니다. 자극 없는 시간을 견디는 능력은 즐거움의 ‘바닥’을 보여줍니다.',
    cues: [
      '실제로 15분을 해보고 적으세요. (타이머, 휴대폰은 다른 방)',
      '몇 분쯤에서 불편해졌나요? 무엇을 하고 싶어졌나요?',
      '여가를 ‘무언가로 채우는 것’이 아니라 ‘비워두는 것’으로 본 적이 있나요?',
    ],
    lensIds: ['wilson-just-think', 'pieper-leisure', 'killingsworth-wandering-mind'],
    tags: ['즐거움', '고독', '지루함', '여가', '실험'],
    minutes: 20,
  },
  {
    id: 'joy-reward-kills',
    domainId: 'joy',
    level: 3,
    kind: 'contrast',
    title: '좋아서 하던 일이 돈이나 평가가 붙자 시들해진 경험이 있나요? 그렇다면 ‘좋아하는 일을 직업으로’는 좋은 조언인가요?',
    why: '외적 보상이 내적 동기를 갉아먹는다는 것은 잘 재현된 발견입니다. 하지만 ‘소명’으로 일하는 사람들도 있습니다. 당신은 어느 조건에서 어느 쪽인가요?',
    cues: [
      '보상이 붙어 시든 일과, 보상이 붙어도 여전히 좋은 일을 하나씩 적어보세요.',
      '차이는 자율성? 평가의 방식? 일의 구조?',
      '조화로운 열정과 강박적 열정 중 지금 당신의 일은 어느 쪽인가요?',
    ],
    lensIds: ['intrinsic-motivation', 'vallerand-passion', 'wrzesniewski-calling'],
    tags: ['즐거움', '보상', '동기', '직업', '열정'],
    minutes: 15,
  },
  {
    id: 'joy-pleasure-suspicion',
    domainId: 'joy',
    level: 3,
    kind: 'contrast',
    title: '즐거움을 추구하는 삶은 얕다는 비판(금욕주의, 유교적 절제, 니체의 ‘최후의 인간’)에 어떻게 답하겠습니까?',
    why: '즐거움을 삶의 중심에 두는 것에 대한 오래된 경계가 있습니다. 반론을 통과해야 당신의 즐거움론은 변명이 아니라 입장이 됩니다.',
    cues: [
      '‘얕은 즐거움’과 ‘깊은 즐거움’을 나눌 수 있나요? 기준은?',
      '에피쿠로스는 절제가 곧 쾌락의 기술이라고 했습니다. 동의하나요?',
      '니체의 ‘최후의 인간’(안락만 추구하는 자)이 당신의 모습과 겹치는 부분은?',
    ],
    lensIds: ['nietzsche', 'epicurus-ataraxia', 'mill-utilitarianism', 'buddhism-dukkha'],
    tags: ['즐거움', '쾌락주의', '금욕', '비판'],
    minutes: 15,
  },
  {
    id: 'joy-suffering-joy',
    domainId: 'joy',
    level: 3,
    kind: 'contrast',
    title: '고통스러운데도 계속하고 싶은 활동(달리기, 매운 음식, 어려운 책)은 무엇이고, 그 즐거움은 어디서 오나요?',
    why: '선택한 고통은 즐거움과 의미의 재료가 됩니다. 이 역설을 이해하면 ‘즐거움 = 편안함’이라는 등식이 깨집니다.',
    cues: [
      '기꺼이 감수하는 고통이 들어 있는 활동 셋을 적으세요.',
      '고통이 빠지면 그 활동의 즐거움도 줄어드나요?',
      '선택한 고통과 강요된 고통의 차이는 무엇인가요?',
    ],
    lensIds: ['bloom-sweet-spot', 'csikszentmihalyi-flow', 'nietzsche'],
    tags: ['즐거움', '고통', '도전', '역설'],
    minutes: 15,
  },
  {
    id: 'joy-synthesis',
    domainId: 'joy',
    level: 4,
    kind: 'synthesis',
    title: '‘나는 ___할 때 즐겁다’를 조건 형태로 정리하고(혼자/함께, 난이도, 피드백, 창작/소비), 이 조건을 다음 한 주 어디에 적용할지 적으세요.',
    why: '즐거움에 대한 이해는 실제 일정에 반영될 때 완성됩니다. 조건 형태로 정리하면 새로운 활동도 미리 판별할 수 있습니다.',
    cues: [
      '조건 3–5개를 ‘~할 때’ 형태로 적으세요. (예: 혼자, 약간 어려운, 결과가 바로 보이는, 만드는)',
      '지난 한 달의 즐거운 순간들이 이 조건에 맞는지 검증하세요.',
      '다음 주 일정에서 이 조건에 맞게 바꿀 수 있는 것 하나는?',
    ],
    prereqIds: ['joy-lost-time', 'joy-kinds'],
    lensIds: ['csikszentmihalyi-flow', 'designing-your-life', 'spinoza-joy'],
    tags: ['즐거움', '종합', '조건', '설계'],
    minutes: 20,
  },

  // ───────────────────────────── 가치 ─────────────────────────────
  {
    id: 'val-choices',
    domainId: 'values',
    level: 1,
    kind: 'experience',
    title: '지난 1년, 무언가를 포기하면서까지 지킨 것이 있나요? 그 선택이 드러내는 가치는 무엇인가요?',
    why: '가치는 말이 아니라 비용을 치른 선택에서 드러납니다. 포기한 것이 클수록 지킨 것의 무게가 분명해집니다.',
    cues: [
      '선택의 장면을 구체적으로 적으세요. 무엇을 잃었고 무엇을 지켰나요?',
      '같은 상황에서 반대로 선택했을 사람은 무엇을 중요하게 여기는 사람인가요?',
      '지킨 것에 이름을 붙인다면? (자유, 정직, 가족, 성장, 안정…)',
    ],
    lensIds: ['revealed-values', 'frankfurt-caring', 'williams-ground-projects'],
    tags: ['가치', '선택', '희생', '경험'],
    minutes: 10,
  },
  {
    id: 'val-anger',
    domainId: 'values',
    level: 1,
    kind: 'experience',
    title: '무엇에 분노하나요? 무엇에 부끄러움을 느끼나요? 강한 감정은 가치가 침해된 신호입니다.',
    why: '감정은 가치 판단을 담고 있습니다. 분노는 ‘이것은 부당하다’, 수치는 ‘이것은 내가 아니다’라는 판단입니다. 감정을 읽으면 가치가 보입니다.',
    cues: [
      '최근 분노한 일 셋: 각각 무엇이 침해되었나요?',
      '최근 부끄러웠던 일: 어떤 기준에 미치지 못했나요? 그 기준은 누구의 것인가요?',
      '감동받은 일도 적어보세요. 감동은 가치가 실현되는 것을 볼 때 옵니다.',
    ],
    lensIds: ['nussbaum-emotions-judgments', 'strohminger-moral-self', 'toegye-sadan-chiljeong'],
    tags: ['가치', '감정', '분노', '수치', '감동'],
    minutes: 10,
  },
  {
    id: 'val-admire',
    domainId: 'values',
    level: 1,
    kind: 'experience',
    title: '존경하는 사람 두 명을 떠올리고, 그들의 어떤 점을 존경하는지 적어보세요. 그것이 당신이 되고 싶은 모습입니다.',
    why: '존경은 가치의 거울입니다. 무엇을 존경하는지는 무엇이 되고 싶은지를 말해줍니다.',
    cues: [
      '유명인보다 직접 아는 사람이 좋습니다.',
      '그들의 성취가 아니라 성품과 행동 방식을 적어보세요.',
      '두 사람의 공통점은? 당신에게 이미 있는 부분과 없는 부분은?',
    ],
    lensIds: ['via-strengths', 'aristotle-eudaimonia', 'confucius-ren'],
    tags: ['가치', '존경', '덕', '모델'],
    minutes: 10,
  },
  {
    id: 'val-rank',
    domainId: 'values',
    level: 2,
    kind: 'definition',
    title: '당신의 핵심 가치 다섯 가지를 고르고 순위를 매기세요. 두 가치가 충돌할 때 어느 쪽이 이기나요?',
    why: '가치는 목록이 아니라 서열일 때 결정을 돕습니다. 도구의 ‘가치 카드 정렬’을 먼저 해보면 이 질문이 쉬워집니다.',
    cues: [
      '다섯 가치를 적고 1–5위를 매기세요.',
      '1위와 2위가 충돌했던 실제 상황을 떠올려보세요. 실제로 무엇이 이겼나요?',
      '순위와 실제 선택이 다르다면, 순위가 틀린 걸까요, 선택이 틀린 걸까요?',
    ],
    lensIds: ['schwartz-values', 'act-values', 'frankfurt-caring'],
    tags: ['가치', '순위', '충돌', '핵심 가치'],
    minutes: 15,
  },
  {
    id: 'val-stated-vs-lived',
    domainId: 'values',
    level: 2,
    kind: 'definition',
    title: '지난주 시간과 돈을 어디에 썼는지 살펴보세요. 그 기록이 말하는 가치와 당신이 말하는 가치는 얼마나 일치하나요?',
    why: '달력과 통장은 가장 정직한 가치 진술서입니다. 말하는 가치와 사는 가치의 간극이 곧 불편함의 출처입니다.',
    cues: [
      '지난주 시간을 크게 다섯 범주로 나눠 비율을 적으세요. 돈도 같은 방식으로.',
      '이 비율만 보고 낯선 사람이 당신의 가치를 추측한다면?',
      '간극이 가장 큰 곳은? 그것은 조정할 것인가요, 받아들일 것인가요?',
    ],
    lensIds: ['revealed-values', 'act-values', 'schwartz-values'],
    tags: ['가치', '시간', '돈', '행동', '간극'],
    minutes: 15,
  },
  {
    id: 'val-inherited',
    domainId: 'values',
    level: 3,
    kind: 'contrast',
    title: '당신의 가치 중 부모·학교·사회가 넘겨준 것은 무엇인가요? 검토 끝에 ‘내 것’으로 다시 채택할 것과 돌려줄 것은?',
    why: '검토 없이 물려받은 가치는 위기 때 낯선 사람의 명령처럼 느껴집니다. 검토를 거쳐 다시 채택한 가치만이 진짜 나의 것입니다.',
    cues: [
      '‘사람은 ___해야 한다’는 문장을 열 개 적고 출처를 표시하세요.',
      '각 문장에 대해: 검토했는가? 동의하는가? 그 이유는?',
      '돌려주기로 한 가치가 있다면, 그것을 내려놓을 때 두려운 것은 무엇인가요?',
    ],
    lensIds: ['marcia-identity-status', 'kegan-self-authoring', 'taylor-authenticity', 'markus-kitayama-self'],
    tags: ['가치', '가족', '사회', '검토', '독립'],
    minutes: 20,
  },
  {
    id: 'val-conflict',
    domainId: 'values',
    level: 3,
    kind: 'contrast',
    title: '성취 vs 관계, 안정 vs 자유, 자기 vs 타인 — 당신 안에서 가장 자주 충돌하는 가치 쌍은? 지금까지 어떻게 타협해왔나요?',
    why: '슈워츠의 가치 이론은 어떤 가치들이 구조적으로 충돌한다고 말합니다. 충돌을 없앨 수는 없지만, 자기만의 타협 규칙을 만들 수는 있습니다.',
    cues: [
      '가장 자주 충돌하는 쌍을 고르고, 최근의 충돌 사례를 적으세요.',
      '지금까지의 타협 방식: 번갈아, 한쪽 희생, 상황별 규칙, 회피?',
      '당신이 존경하는 사람은 이 충돌을 어떻게 다루나요?',
    ],
    lensIds: ['schwartz-values', 'berlin-two-liberties', 'williams-ground-projects'],
    tags: ['가치', '충돌', '타협', '갈등'],
    minutes: 15,
  },
  {
    id: 'val-universal',
    domainId: 'values',
    level: 3,
    kind: 'contrast',
    title: '당신의 가치가 모든 사람에게도 옳다고 믿나요, 아니면 당신에게만 옳은가요? 그 입장의 근거는 무엇인가요?',
    why: '‘나에게만 옳다’는 겸손해 보이지만 타인의 잘못을 말할 수 없게 만들고, ‘모두에게 옳다’는 오만해 보이지만 정의를 말할 수 있게 합니다. 어디에 설 것인가요?',
    cues: [
      '당신의 가치 중 모든 사람에게 요구할 수 있는 것과 당신만의 취향인 것을 나누세요.',
      '전자의 근거는? (이성, 인간의 조건, 공감, 전통…)',
      '다른 문화의 가치와 충돌할 때 어떻게 판단하나요?',
    ],
    lensIds: ['kant-autonomy', 'nussbaum-capabilities', 'mill-liberty', 'confucius-ren'],
    tags: ['가치', '보편', '상대주의', '윤리'],
    minutes: 20,
  },
  {
    id: 'val-synthesis',
    domainId: 'values',
    level: 4,
    kind: 'synthesis',
    title: '‘나는 ___을 ___보다 중요하게 여긴다’는 문장 세 개로 가치 서열을 선언하고, 이를 어기게 되는 상황과 그때의 규칙을 적으세요.',
    why: '선언된 서열은 결정의 속도를 높이고 후회를 줄입니다. 예외 규칙까지 적어야 실제로 작동합니다.',
    cues: [
      '세 문장을 쓰고, 각 문장이 최근 결정에서 지켜졌는지 확인하세요.',
      '어기게 되는 상황(피로, 압력, 공포)과 그때 자신에게 할 말을 정하세요.',
      '이 서열을 가까운 사람에게 말한다면 어떤 반응이 예상되나요?',
    ],
    prereqIds: ['val-rank'],
    lensIds: ['act-values', 'frankfurt-caring', 'schwartz-values'],
    tags: ['가치', '종합', '서열', '규칙'],
    minutes: 20,
  },

  // ───────────────────────────── 자아와 이야기 ─────────────────────────────
  {
    id: 'id-scenes',
    domainId: 'identity',
    level: 1,
    kind: 'experience',
    title: '당신 인생의 결정적 장면 다섯 개를 골라 제목을 붙여보세요. (전환점, 절정, 바닥, 시작, 최근)',
    why: '자아는 사실의 목록이 아니라 이야기입니다. 핵심 장면을 고르는 행위 자체가 당신이 어떤 서사로 자신을 이해하는지 보여줍니다.',
    cues: [
      '각 장면을 두세 문장으로: 무슨 일이, 누구와, 그때 나는 무엇을 느꼈나.',
      '각 장면이 지금의 나에게 남긴 것 한 가지.',
      '다섯 장면을 잇는 하나의 주제가 있나요?',
    ],
    lensIds: ['mcadams-narrative-identity', 'montaigne-essays'],
    tags: ['자아', '이야기', '장면', '서사'],
    minutes: 20,
  },
  {
    id: 'id-descriptions',
    domainId: 'identity',
    level: 1,
    kind: 'experience',
    title: '‘나는 ___이다’를 열 번 완성해보세요. 역할(직업, 가족), 성향, 가치가 각각 몇 개인가요?',
    why: '스무 진술 검사(TST)의 축약판입니다. 무엇이 먼저 떠오르고 무엇이 없는지가 자기개념의 구조를 보여줍니다.',
    cues: [
      '생각하지 말고 빠르게 열 개를 적으세요.',
      '역할/성향/가치/관계/신체/취향으로 분류하고 개수를 세세요.',
      '열 개 중 5년 전에도 썼을 문장은 몇 개인가요?',
    ],
    lensIds: ['self-concept-clarity', 'twenty-statements-test', 'markus-kitayama-self', 'strohminger-moral-self'],
    tags: ['자아', '자기개념', '정체성', '역할'],
    minutes: 10,
  },
  {
    id: 'id-others-see',
    domainId: 'identity',
    level: 1,
    kind: 'experience',
    title: '가까운 사람 셋이 당신을 한 문장으로 묘사한다면? 당신의 자기 묘사와 어디가 다른가요?',
    why: '자기이해에는 안에서 보는 눈과 밖에서 보는 눈이 모두 필요합니다. 둘의 차이가 맹점입니다.',
    cues: [
      '실제로 물어볼 수 있다면 물어보세요. 아니면 최대한 정직하게 추측하세요.',
      '세 문장의 공통점과, 당신의 자기 묘사에 없는 요소는?',
      '그 차이가 불편하다면 무엇이 불편한가요?',
    ],
    lensIds: ['eurich-insight', 'nisbett-wilson-introspection'],
    tags: ['자아', '타인', '맹점', '피드백'],
    minutes: 10,
  },
  {
    id: 'id-continuity',
    domainId: 'identity',
    level: 2,
    kind: 'definition',
    title: '10년 전의 당신과 지금의 당신이 ‘같은 사람’인 이유는 무엇인가요? 무엇이 바뀌었고 무엇이 남았나요?',
    why: '우리는 과거의 변화는 크게, 미래의 변화는 작게 봅니다(역사의 종말 착각). 무엇이 나를 ‘같은 나’로 묶는지 정해야 미래의 나를 위한 결정이 가능합니다.',
    cues: [
      '바뀐 것(가치, 취향, 관계, 목표)과 남은 것을 두 열로 적으세요.',
      '‘같은 사람’의 근거는 기억? 몸? 성격? 관계? 이야기?',
      '10년 뒤의 당신은 지금과 얼마나 다를까요? 그 추정은 믿을 만한가요?',
    ],
    prereqIds: ['id-scenes'],
    lensIds: ['parfit-identity', 'hume-bundle', 'end-of-history-illusion', 'mcadams-narrative-identity'],
    tags: ['자아', '연속성', '변화', '시간'],
    minutes: 15,
  },
  {
    id: 'id-true-self',
    domainId: 'identity',
    level: 2,
    kind: 'definition',
    title: '‘진짜 나’라는 것이 있다고 믿나요? 있다면 그것은 발견되는 것인가요, 만들어지는 것인가요?',
    why: '‘진짜 나’를 믿는 사람은 의미감이 높지만, 그 믿음은 회피의 핑계가 되기도 합니다. 발견/발명 중 어느 쪽에 서느냐가 자기이해의 방법을 바꿉니다.',
    cues: [
      '‘진짜 나답지 않았다’고 느낀 순간과 ‘진짜 나였다’고 느낀 순간을 적어보세요.',
      '진짜 나는 좋은 면만 가진 존재인가요? 그렇다면 그것은 사실인가요, 이상인가요?',
      '‘진짜 나는 없고 만들어갈 뿐’이라는 입장의 장점과 위험은?',
    ],
    lensIds: ['schlegel-true-self', 'sartre-existentialism', 'buddhism-anatta', 'taylor-authenticity'],
    tags: ['자아', '진정성', '진짜 나', '실존'],
    minutes: 15,
  },
  {
    id: 'id-story-genre',
    domainId: 'identity',
    level: 2,
    kind: 'definition',
    title: '당신의 인생 이야기는 어떤 장르인가요? 구원 서사(나쁜 일→좋은 결과)와 오염 서사(좋은 일→나쁜 결과) 중 어느 패턴이 더 많나요?',
    why: '같은 사건도 어떻게 이야기하느냐에 따라 삶의 만족과 생성감이 달라집니다. 서사 패턴은 바꿀 수 있는 것입니다.',
    cues: [
      '결정적 장면들을 구원/오염/중립으로 분류하세요.',
      '오염 서사로 기억되는 사건을 구원 서사로 다시 써본다면? (거짓말이 아니라 다른 강조)',
      '당신 이야기의 주인공은 어떤 인물인가요? 조연은?',
    ],
    prereqIds: ['id-scenes'],
    lensIds: ['mcadams-narrative-identity', 'frankl-logotherapy'],
    tags: ['자아', '서사', '구원', '오염', '이야기'],
    minutes: 15,
  },
  {
    id: 'id-no-self',
    domainId: 'identity',
    level: 3,
    kind: 'contrast',
    title: '‘나’라는 것은 감각과 기억의 다발일 뿐이라는 주장(흄, 불교)을 받아들이면 당신의 삶에서 무엇이 달라지나요?',
    why: '고정된 자아가 없다는 관점은 위협적으로 들리지만, 실제로는 변화의 자유와 집착의 완화를 줄 수 있습니다. 시험해볼 가치가 있습니다.',
    cues: [
      '내면을 들여다보며 ‘나’ 자체를 찾아보세요. 감각·생각·감정 말고 무엇이 발견되나요?',
      '자아가 다발이라면 ‘나답게’라는 말은 무슨 뜻이 되나요?',
      '이 관점이 당신의 불안이나 집착 중 무엇을 가볍게 하나요? 무엇을 잃게 하나요?',
    ],
    lensIds: ['hume-bundle', 'buddhism-anatta', 'parfit-identity'],
    tags: ['자아', '무아', '흄', '불교', '대조'],
    minutes: 15,
  },
  {
    id: 'id-authored',
    domainId: 'identity',
    level: 3,
    kind: 'contrast',
    title: '당신은 지금 ‘주어진 대본’을 사는 중인가요, ‘스스로 쓴 대본’을 사는 중인가요? 케건의 사회화된 자아/자기저작 자아 구분으로 본다면?',
    why: '케건은 성인 발달의 핵심 전환을 ‘타인의 기대에 의해 정의되는 자아’에서 ‘스스로의 체계로 판단하는 자아’로의 이동으로 봅니다. 이 서비스의 목표가 바로 그 이동입니다.',
    cues: [
      '최근 중요한 결정에서 기준은 누구의 것이었나요?',
      '스스로 쓴 대본이라 느끼는 영역과 아닌 영역을 나눠보세요.',
      '자기저작을 넘어, 자신의 체계마저 상대화할 수 있는 영역이 있나요?',
    ],
    lensIds: ['kegan-self-authoring', 'marcia-identity-status', 'kierkegaard-self', 'heidegger-being-toward-death'],
    tags: ['자아', '자기저작', '발달', '독립', '대본'],
    minutes: 15,
  },
  {
    id: 'id-introspection-limits',
    domainId: 'identity',
    level: 3,
    kind: 'contrast',
    title: '내면을 들여다보는 일이 오히려 나를 오해하게 만들 수 있다는 연구에 비추어, 당신은 자기이해를 어떻게 검증하나요?',
    why: '우리는 자신의 행동 이유를 ‘아는’ 것이 아니라 ‘지어내는’ 경우가 많습니다. 내성(introspection)의 한계를 알면 자기이해의 방법이 달라집니다: 이유를 묻기보다 패턴을 관찰하기.',
    cues: [
      '스스로에 대해 확신했다가 틀렸던 경험은?',
      '당신의 자기 인식 중 행동 기록으로 검증 가능한 것은 무엇인가요?',
      '‘왜’ 대신 ‘무엇’으로 묻는 연습을 해보세요: 왜 화났나 → 무엇이 그 상황에서 중요했나.',
    ],
    prereqIds: ['id-others-see'],
    lensIds: ['nisbett-wilson-introspection', 'eurich-insight', 'self-concept-clarity'],
    tags: ['자아', '내성', '검증', '자기인식', '방법'],
    minutes: 15,
  },
  {
    id: 'id-synthesis',
    domainId: 'identity',
    level: 4,
    kind: 'synthesis',
    title: '‘나는 ___한 사람이며, ___를 향해 가고 있다’를 쓰고, 이 문장을 5년 뒤에도 유지하고 싶은지, 바꾸고 싶은지 적으세요.',
    why: '정체성 진술은 고정된 사실이 아니라 방향 선언입니다. 유지/변경 의사를 함께 적으면 진술이 감옥이 아니라 나침반이 됩니다.',
    cues: [
      '한 문장 → 그 근거가 되는 장면 둘 → 어긋나는 장면 하나.',
      '이 문장이 사실이 되려면 앞으로 무엇을 계속해야 하나요?',
      '5년 뒤 이 문장을 다시 읽을 자신에게 한 마디.',
    ],
    prereqIds: ['id-scenes', 'id-descriptions'],
    lensIds: ['mcadams-narrative-identity', 'kegan-self-authoring', 'montaigne-essays'],
    tags: ['자아', '종합', '정체성', '방향'],
    minutes: 20,
  },

  // ───────────────────────────── 관계와 사랑 ─────────────────────────────
  {
    id: 'rel-alive',
    domainId: 'relationships',
    level: 1,
    kind: 'experience',
    title: '누구와 있을 때 가장 ‘살아 있다’고 느끼나요? 그 관계의 어떤 요소가 그렇게 만드나요?',
    why: '좋은 관계의 요소(안전, 인정, 자극, 함께 있음)를 구체적으로 알아야 관계를 고를 수 있습니다.',
    cues: [
      '한 사람과의 최근 장면을 적으세요. 무엇을 했고 어떤 대화가 있었나요?',
      '그 관계에서 당신은 어떤 사람이 되나요?',
      '살아 있음을 만드는 요소는 그 사람인가요, 그 관계의 방식인가요?',
    ],
    lensIds: ['harvard-adult-development', 'buber-i-thou', 'sdt-needs'],
    tags: ['관계', '경험', '살아 있음', '친밀'],
    minutes: 10,
  },
  {
    id: 'rel-drain',
    domainId: 'relationships',
    level: 1,
    kind: 'experience',
    title: '함께 있으면 작아지는 관계는? 그 관계를 유지하는 이유는 무엇인가요?',
    why: '유지 이유(의무, 두려움, 습관, 실익)를 정직하게 적으면 관계의 종류가 보입니다. 모든 관계를 끊을 필요는 없지만, 이름은 붙여야 합니다.',
    cues: [
      '장면 하나: 어떤 말이나 행동이 당신을 작아지게 했나요?',
      '유지 이유를 적고, 그것이 유용함/즐거움/성품 중 어디에 속하는지 보세요.',
      '이 관계에서 당신이 바꿀 수 있는 것과 없는 것은?',
    ],
    caution: '관계의 문제를 전부 자신의 탓으로 돌리고 있지 않은지 살펴보세요.',
    lensIds: ['aristotle-friendship', 'fromm-art-of-loving'],
    tags: ['관계', '소모', '경계', '경험'],
    minutes: 10,
  },
  {
    id: 'rel-define-love',
    domainId: 'relationships',
    level: 2,
    kind: 'definition',
    title: '당신에게 사랑은 감정인가요, 행위인가요, 의지인가요? 사랑이 ‘식었다’는 말은 무엇을 뜻하나요?',
    why: '사랑을 감정으로 보면 사랑은 일어나는 것이고, 행위로 보면 하는 것입니다. 이 정의가 관계의 위기에서 무엇을 할지를 결정합니다.',
    cues: [
      '사랑받았다고 느낀 장면: 그것은 상대의 감정이었나요, 행동이었나요?',
      '프롬의 네 요소(관심, 책임, 존중, 앎) 중 당신이 잘하는 것과 못하는 것은?',
      '‘식었다’가 감정의 소멸이라면 사랑은 통제 밖이고, 행위의 중단이라면 통제 안입니다. 어느 쪽인가요?',
    ],
    lensIds: ['fromm-art-of-loving', 'hooks-love-as-action', 'murdoch-attention'],
    tags: ['관계', '사랑', '정의', '감정', '행위'],
    minutes: 15,
  },
  {
    id: 'rel-friendship-kinds',
    domainId: 'relationships',
    level: 2,
    kind: 'definition',
    title: '당신의 관계들을 ‘유용함·즐거움·덕(성품)’의 우정으로 분류해보세요. 마지막 종류는 몇 개인가요?',
    why: '아리스토텔레스는 상대의 성품 자체를 사랑하는 우정만이 오래간다고 했습니다. 분류해보면 관계 포트폴리오의 구조가 보입니다.',
    cues: [
      '자주 만나는 열 명을 적고 분류하세요. 겹쳐도 됩니다.',
      '덕의 우정이 적다면: 그런 우정을 만들 시간과 조건이 있었나요?',
      '당신은 남에게 어떤 종류의 친구인가요?',
    ],
    lensIds: ['aristotle-friendship'],
    tags: ['관계', '우정', '분류', '아리스토텔레스'],
    minutes: 15,
  },
  {
    id: 'rel-alone-vs-together',
    domainId: 'relationships',
    level: 2,
    kind: 'definition',
    title: '혼자 있는 시간과 함께 있는 시간 중 무엇이 더 필요한 사람인가요? 그 비율은 지금 적절한가요?',
    why: '고독의 필요와 연결의 필요는 사람마다 비율이 다르고, 문화는 한쪽을 정상으로 규정합니다. 자기 비율을 아는 것이 관계 설계의 시작입니다.',
    cues: [
      '지난주 혼자/함께 시간을 대략 계산하세요.',
      '혼자 있을 때 회복되나요, 불안한가요? 함께 있을 때 채워지나요, 소모되나요?',
      '이상적 비율을 정하고, 현재와의 차이를 적으세요.',
    ],
    lensIds: ['markus-kitayama-self', 'wilson-just-think', 'attachment-theory'],
    tags: ['관계', '고독', '내향', '외향', '비율'],
    minutes: 10,
  },
  {
    id: 'rel-other-as-means',
    domainId: 'relationships',
    level: 3,
    kind: 'contrast',
    title: '관계에서 타인을 ‘나의 행복을 위한 수단’으로 대한 적은 언제였나요? 부버의 ‘나–너’ 관계는 어떻게 다른가요?',
    why: '행복론이 자기중심적일수록 관계는 도구가 됩니다. 부버와 레비나스는 타인을 대상이 아닌 ‘너’로 만나는 것이 오히려 나를 만든다고 말합니다.',
    cues: [
      '정직하게: 누군가를 ‘써먹은’ 순간 하나.',
      '그 사람을 ‘너’로 만났던 순간과 비교하면 무엇이 달랐나요?',
      '타인을 수단으로 대하지 않으면서도 나의 필요를 챙길 수 있나요?',
    ],
    lensIds: ['buber-i-thou', 'levinas-other', 'kant-autonomy'],
    tags: ['관계', '타자', '윤리', '수단', '부버'],
    minutes: 15,
  },
  {
    id: 'rel-independence',
    domainId: 'relationships',
    level: 3,
    kind: 'contrast',
    title: '‘남에게 의존하지 않는 삶’이 이상인가요? 상호의존을 성숙으로 보는 관점과 대조해보세요.',
    why: '독립을 성숙으로 보는 것은 특정 문화의 관점입니다. 애착 연구는 안전한 의존이 오히려 자율을 낳는다고 말합니다.',
    cues: [
      '의존이 부끄러웠던 경험과 의존이 힘이 된 경험을 하나씩.',
      '당신의 애착 방식(안정, 불안, 회피)은 관계에서 어떻게 드러나나요?',
      '‘건강한 의존’을 정의해본다면?',
    ],
    lensIds: ['markus-kitayama-self', 'attachment-theory', 'confucius-ren', 'fromm-art-of-loving'],
    tags: ['관계', '독립', '의존', '애착', '문화'],
    minutes: 15,
  },
  {
    id: 'rel-obligation',
    domainId: 'relationships',
    level: 3,
    kind: 'contrast',
    title: '가족·효·의리 같은 주어진 의무는 어디까지 나의 것인가요? 유교적 관계윤리와 개인주의 사이에서 당신의 자리는?',
    why: '한국에서 관계는 선택 이전에 주어집니다. 주어진 의무를 전부 거부하는 것도, 전부 받아들이는 것도 검토가 아닙니다.',
    cues: [
      '지금 지고 있는 관계의 의무를 적고, 각각에 대해 ‘동의하는가’를 표시하세요.',
      '동의하지 않지만 지키는 의무가 있다면 왜 지키나요?',
      '유교의 관계적 자아(仁, 恕)에서 배울 것과 버릴 것은?',
    ],
    lensIds: ['confucius-ren', 'toegye-sadan-chiljeong', 'mill-liberty', 'taylor-authenticity'],
    tags: ['관계', '가족', '의무', '유교', '개인주의'],
    minutes: 15,
  },
  {
    id: 'rel-synthesis',
    domainId: 'relationships',
    level: 4,
    kind: 'synthesis',
    title: '‘관계는 내 삶에서 ___이다’를 쓰고, 그에 따라 시간을 더 줄 사람과 줄일 관계를 구체적으로 적으세요.',
    why: '관계에 대한 입장은 시간 배분으로 검증됩니다. 이름을 적는 순간 철학이 실천이 됩니다.',
    cues: [
      '한 문장 → 이 문장이 행복/의미에 대한 당신의 입장과 일치하는지 확인.',
      '더 줄 사람 둘, 줄일 관계 하나 — 그리고 첫 행동.',
      '이 결정이 어려운 이유가 있다면 무엇인가요?',
    ],
    prereqIds: ['rel-alive', 'rel-friendship-kinds'],
    lensIds: ['harvard-adult-development', 'aristotle-friendship', 'fromm-art-of-loving'],
    tags: ['관계', '종합', '시간', '우선순위'],
    minutes: 20,
  },

  // ───────────────────────────── 일과 소명 ─────────────────────────────
  {
    id: 'work-best-day',
    domainId: 'work',
    level: 1,
    kind: 'experience',
    title: '일하며 가장 만족스러웠던 하루를 떠올려보세요. 무엇을 만들었고, 누가 알아봐주었고, 얼마나 자율적이었나요?',
    why: '좋은 일의 조건은 보편적 원칙보다 당신의 최고의 하루에 더 정확히 들어 있습니다.',
    cues: [
      '그날의 시간표를 대략 복원해보세요.',
      '만든 것, 알아봐준 사람, 스스로 결정한 것, 배운 것을 각각 적으세요.',
      '그날과 보통날의 차이 중 당신이 재현할 수 있는 것은?',
    ],
    lensIds: ['ariely-legos', 'sdt-needs', 'csikszentmihalyi-flow'],
    tags: ['일', '경험', '만족', '자율'],
    minutes: 10,
  },
  {
    id: 'work-worst',
    domainId: 'work',
    level: 1,
    kind: 'experience',
    title: '일이 가장 공허했던 때는? 무엇으로부터 분리되어 있었나요(결과물, 과정, 동료, 자기 자신)?',
    why: '마르크스의 소외 개념은 여전히 정확합니다. 무엇으로부터 분리되어 있었는지 알면 공허함의 정체가 보입니다.',
    cues: [
      '장면 하나: 어떤 일을 하고 있었고 왜 공허했나요?',
      '결과물이 보이지 않았나? 과정이 통제 밖이었나? 동료가 경쟁자였나? 나답지 않았나?',
      '같은 일을 공허하지 않게 하는 사람이 있다면 무엇이 다른가요?',
    ],
    lensIds: ['marx-alienation', 'han-burnout-society'],
    tags: ['일', '공허', '소외', '번아웃'],
    minutes: 10,
  },
  {
    id: 'work-jcc',
    domainId: 'work',
    level: 2,
    kind: 'definition',
    title: '지금의 일은 당신에게 생계(job), 경력(career), 소명(calling) 중 무엇인가요? 같은 일이라도 다르게 볼 수 있나요?',
    why: '연구에 따르면 같은 직무 안에서도 세 태도가 고루 나뉩니다. 일의 종류가 아니라 일을 보는 틀이 경험을 결정합니다.',
    cues: [
      '지금 일을 세 틀 각각으로 서술해보세요. 어느 서술이 가장 자연스럽나요?',
      '소명으로 보는 데 방해가 되는 것은? (일 자체, 조직, 나의 태도)',
      '소명이어야만 좋은 일인가요? 생계로 보는 것의 장점은?',
    ],
    lensIds: ['wrzesniewski-calling', 'weber-beruf', 'ikigai-kamiya'],
    tags: ['일', '소명', '경력', '생계', '태도'],
    minutes: 15,
  },
  {
    id: 'work-for-what',
    domainId: 'work',
    level: 2,
    kind: 'definition',
    title: '일은 무엇을 위한 것인가요? 돈, 인정, 성장, 기여, 자기표현… 돈이 필요 없다면 무엇을 하고 있을까요?',
    why: '‘일은 무엇을 위한 것인가’에 대한 답(Workview)은 삶에 대한 답(Lifeview)과 맞물려야 합니다. 어긋나면 성공해도 허무합니다.',
    cues: [
      '일의 목적을 다섯 개 적고 비율을 매기세요.',
      '돈이 해결되었다고 가정하고, 내일 아침 무엇을 하러 나갈지 적으세요.',
      '그 답과 지금 하는 일의 거리는 얼마나 되나요?',
    ],
    lensIds: ['arendt-vita-activa', 'sennett-craftsman', 'pieper-leisure'],
    tags: ['일', '목적', '돈', '기여', '표현'],
    minutes: 15,
  },
  {
    id: 'work-good-work',
    domainId: 'work',
    level: 2,
    kind: 'definition',
    title: '‘좋은 일’의 기준을 세 가지로 정리해보세요. 지금 일은 그중 몇 개를 충족하나요?',
    why: '기준이 없으면 모든 제안이 그럴듯해 보입니다. 세 기준은 결정을 빠르게 하고, 충족 개수는 현재를 진단합니다.',
    cues: [
      '최고의 하루와 최악의 하루에서 추출한 조건을 기준으로 다듬으세요.',
      '기준 각각에 대해 ‘이것이 없어도 좋은 일인가’로 시험하세요.',
      '지금 일이 충족하지 못하는 기준은 바꿀 수 있는 것인가요?',
    ],
    prereqIds: ['work-best-day'],
    lensIds: ['sennett-craftsman', 'sdt-needs', 'wrzesniewski-calling'],
    tags: ['일', '기준', '좋은 일', '진단'],
    minutes: 15,
  },
  {
    id: 'work-self-exploitation',
    domainId: 'work',
    level: 3,
    kind: 'contrast',
    title: '‘할 수 있다’는 긍정성이 스스로를 착취하게 만든다는 한병철의 진단은 당신에게 얼마나 해당되나요?',
    why: '외부의 강제가 아니라 자기 최적화의 명령이 사람을 소진시킨다는 진단은 성과 사회 한국에서 특히 아픕니다. 어디까지 동의하는지 정해야 합니다.',
    cues: [
      '최근 스스로에게 부과한 요구를 적어보세요. 누가 시켰나요?',
      '‘더 잘할 수 있다’는 생각이 당신을 밀어올린 경우와 갉아먹은 경우.',
      '이 진단의 반론: 성취 압력 없이 성장이 가능한가요?',
    ],
    lensIds: ['han-burnout-society', 'weber-beruf', 'zhuangzi-useless-tree'],
    tags: ['일', '번아웃', '성과사회', '자기착취'],
    minutes: 15,
  },
  {
    id: 'work-leisure',
    domainId: 'work',
    level: 3,
    kind: 'contrast',
    title: '여가는 일을 위한 회복인가요, 그 자체로 삶의 중심인가요? 여가를 ‘무위’로 보는 관점을 검토해보세요.',
    why: '피퍼는 여가가 일의 부속물이 아니라 문화의 토대라고 했습니다. 여가를 어떻게 보느냐가 일의 위치를 결정합니다.',
    cues: [
      '지난 주말은 회복이었나요, 소비였나요, 여가였나요?',
      '‘아무것도 하지 않음’을 견딜 수 있나요? 그것이 생산적이지 않아도 괜찮나요?',
      '여가가 중심이라면 일은 무엇이 되나요?',
    ],
    lensIds: ['pieper-leisure', 'arendt-vita-activa', 'laozi-wuwei', 'play-huizinga'],
    tags: ['일', '여가', '휴식', '무위', '놀이'],
    minutes: 15,
  },
  {
    id: 'work-passion-advice',
    domainId: 'work',
    level: 3,
    kind: 'contrast',
    title: '‘열정을 따르라’는 조언의 문제점은 무엇인가요? 열정은 발견되나요, 길러지나요?',
    why: '열정을 ‘발견’으로 보면 없는 사람은 실패자가 되고, ‘개발’로 보면 어떤 일에서든 길러질 수 있습니다. 당신의 경험은 어느 쪽을 지지하나요?',
    cues: [
      '열정이 생긴 일은 처음부터 좋았나요, 잘하게 되면서 좋아졌나요?',
      '조화로운 열정과 강박적 열정의 차이를 당신의 사례로 설명해보세요.',
      '열정이 없어도 좋은 일을 할 수 있나요? 장인의 태도로 본다면?',
    ],
    lensIds: ['vallerand-passion', 'wrzesniewski-calling', 'sennett-craftsman', 'intrinsic-motivation'],
    tags: ['일', '열정', '조언', '개발', '발견'],
    minutes: 15,
  },
  {
    id: 'work-synthesis',
    domainId: 'work',
    level: 4,
    kind: 'synthesis',
    title: '‘나에게 일은 ___이며, 나는 ___한 일을 ___한 방식으로 하고 싶다’를 쓰고, 현재와의 간극과 첫 조정을 적으세요.',
    why: '일에 대한 철학은 진로 결정의 나침반입니다. 간극을 적으면 불만이 방향으로 바뀝니다.',
    cues: [
      '한 문장 → 이 문장이 행복·의미·가치의 입장과 충돌하지 않는지 확인.',
      '현재와의 간극을 세 가지로.',
      '이번 달 안에 할 수 있는 첫 조정 하나.',
    ],
    prereqIds: ['work-jcc'],
    lensIds: ['wrzesniewski-calling', 'sennett-craftsman', 'arendt-vita-activa'],
    tags: ['일', '종합', '진로', '조정'],
    minutes: 20,
  },

  // ───────────────────────────── 고통과 감정 ─────────────────────────────
  {
    id: 'suf-recent',
    domainId: 'suffering',
    level: 1,
    kind: 'experience',
    title: '최근 겪은 힘든 일을 3인칭으로(당신의 이름을 써서) 서술해보세요. 시점을 바꾸니 무엇이 보이나요?',
    why: '자기 거리두기(3인칭 서술)는 반추를 줄이고 통찰을 늘린다는 것이 반복 검증되었습니다. 힘든 일을 다루는 첫 기술입니다.',
    cues: [
      '“OO은 그날 …” 형식으로, 사실 → 감정 → 그 사람이 필요했던 것 순서로 적으세요.',
      '친구에게 이 일이 일어났다면 뭐라고 말해줄 건가요?',
      '1인칭으로 쓸 때와 무엇이 달랐나요?',
    ],
    caution: '압도되면 멈추세요. 이 서비스는 치료를 대신하지 않습니다. 위기라면 109(자살예방상담) 또는 1577-0199에 연락하세요.',
    lensIds: ['kross-self-distancing', 'pennebaker-expressive-writing'],
    tags: ['고통', '거리두기', '서술', '경험'],
    minutes: 15,
  },
  {
    id: 'suf-emotion-map',
    domainId: 'suffering',
    level: 1,
    kind: 'experience',
    title: '지난주 가장 강했던 감정 세 개와, 그 감정이 ‘평가한’ 것(무엇이 위협받았나, 무엇이 중요했나)을 적어보세요.',
    why: '감정은 소음이 아니라 판단입니다. 감정이 무엇을 평가했는지 읽으면 감정이 정보가 됩니다.',
    cues: [
      '감정 이름을 정확히 붙이세요. (화 → 억울함? 실망? 모욕감?)',
      '각 감정이 보호하려던 가치나 필요는?',
      '그 평가가 정확했나요? 과했나요?',
    ],
    lensIds: ['nussbaum-emotions-judgments', 'spinoza-joy', 'gross-reappraisal'],
    tags: ['감정', '평가', '가치', '이름 붙이기'],
    minutes: 10,
  },
  {
    id: 'suf-second-arrow',
    domainId: 'suffering',
    level: 2,
    kind: 'definition',
    title: '고통(1차 화살)과 고통에 대한 고통(2차 화살: 자책, 반추, ‘왜 하필 나’)을 구분해보세요. 당신의 고통 중 2차 화살은 몇 %인가요?',
    why: '불교의 두 번째 화살 비유는 고통의 상당 부분이 고통에 대한 반응이라는 것을 보여줍니다. 그 부분은 줄일 수 있습니다.',
    cues: [
      '최근의 고통 하나를 1차/2차로 나누세요.',
      '2차 화살의 전형적 문장은? (‘나는 왜 늘’, ‘이러면 안 되는데’)',
      '2차 화살을 쏘지 않는다면 그 고통은 어떤 크기인가요?',
    ],
    lensIds: ['buddhism-dukkha', 'stoicism-dichotomy', 'rumination-vs-reflection'],
    tags: ['고통', '반추', '자책', '불교'],
    minutes: 15,
  },
  {
    id: 'suf-meaningful-pain',
    domainId: 'suffering',
    level: 2,
    kind: 'definition',
    title: '기꺼이 감수하는 고통과 그렇지 않은 고통의 차이는 무엇인가요? 무엇이 고통을 ‘견딜 만한 것’으로 만드나요?',
    why: '견딜 수 있는 고통에는 대개 이유, 선택, 끝, 동료 중 하나가 있습니다. 이 요소를 알면 견딜 수 없는 고통에 무엇을 더해야 하는지 보입니다.',
    cues: [
      '감수하는 고통(운동, 육아, 공부)과 감수하기 힘든 고통을 나란히.',
      '차이는 선택했는가? 의미가 있는가? 끝이 보이는가? 혼자인가?',
      '견디기 힘든 고통에 이 요소 중 하나를 더할 수 있나요?',
    ],
    lensIds: ['frankl-logotherapy', 'bloom-sweet-spot', 'nietzsche'],
    tags: ['고통', '의미', '선택', '인내'],
    minutes: 15,
  },
  {
    id: 'suf-avoid',
    domainId: 'suffering',
    level: 2,
    kind: 'definition',
    title: '당신이 감정을 다루는 기본 전략은 억누르기, 피하기, 다시 해석하기, 표현하기 중 무엇인가요? 그 전략의 비용은?',
    why: '억제는 단기적으로 편하지만 장기 비용이 크고, 재해석은 어렵지만 비용이 낮습니다. 기본 전략을 알아야 바꿀 수 있습니다.',
    cues: [
      '최근 강한 감정 상황에서 실제로 무엇을 했나요?',
      '그 전략이 어릴 때 어디서 배운 것인지 떠올려보세요.',
      '비용: 관계? 몸? 판단력? 어디서 청구되나요?',
    ],
    lensIds: ['gross-reappraisal', 'pennebaker-expressive-writing', 'act-values'],
    tags: ['감정', '조절', '억제', '재해석', '전략'],
    minutes: 15,
  },
  {
    id: 'suf-stoic-test',
    domainId: 'suffering',
    level: 3,
    kind: 'contrast',
    title: '‘통제할 수 없는 것에 대한 판단을 바꾸라’는 스토아의 처방은 어디까지 옳고 어디서부터 체념이 되나요?',
    why: '스토아 철학은 강력하지만, 바꿀 수 있는 부당함까지 받아들이게 만들 위험이 있습니다. 경계선을 스스로 그어야 합니다.',
    cues: [
      '지금의 고통 하나를 ‘통제 가능/불가능’으로 나눠보세요.',
      '판단을 바꾸는 것이 지혜였던 경험과 회피였던 경험.',
      '누스바움처럼 ‘감정은 정당한 판단일 수 있다’는 반론을 어떻게 받나요?',
    ],
    lensIds: ['stoicism-dichotomy', 'nussbaum-emotions-judgments', 'frankl-logotherapy'],
    tags: ['고통', '스토아', '수용', '체념', '대조'],
    minutes: 15,
  },
  {
    id: 'suf-growth',
    domainId: 'suffering',
    level: 3,
    kind: 'contrast',
    title: '고통이 사람을 성장시킨다는 말을 믿나요? 당신에게 성장으로 이어진 고통과 그냥 상처로 남은 고통의 차이는?',
    why: '외상 후 성장은 실재하지만 자동적이지 않습니다. 성장의 조건(의미 만들기, 지지, 시간)을 알면 ‘고통은 좋은 것’이라는 상투어를 넘을 수 있습니다.',
    cues: [
      '성장으로 이어진 고통: 그 사이에 무엇이 있었나요? (사람, 이야기, 시간)',
      '상처로 남은 고통: 무엇이 없었나요?',
      '‘고통 없이 성장할 수 있다’는 반론에 대해서는?',
    ],
    lensIds: ['post-traumatic-growth', 'nietzsche', 'frankl-logotherapy'],
    tags: ['고통', '성장', '외상', '회복'],
    minutes: 15,
  },
  {
    id: 'suf-cultural',
    domainId: 'suffering',
    level: 3,
    kind: 'contrast',
    title: '한(恨)·정(情)처럼 문화가 준 감정 언어가 당신의 느낌을 규정하나요? 다른 언어로 이름 붙이면 달라지나요?',
    why: '감정은 문화가 준 개념으로 경험됩니다. 같은 느낌도 ‘한’으로 부르면 오래 품게 되고, ‘슬픔’으로 부르면 흘려보내기 쉬울 수 있습니다.',
    cues: [
      '당신이 자주 쓰는 감정 단어 열 개를 적고, 그중 한국어 특유의 것은?',
      '가족이 감정을 표현하던 방식이 당신의 감정 어휘에 남아 있나요?',
      '어떤 감정에 새 이름을 붙이면 다르게 다룰 수 있을까요?',
    ],
    lensIds: ['jeong-han', 'nussbaum-emotions-judgments', 'markus-kitayama-self'],
    tags: ['감정', '문화', '한', '정', '언어'],
    minutes: 15,
  },
  {
    id: 'suf-synthesis',
    domainId: 'suffering',
    level: 4,
    kind: 'synthesis',
    title: '‘고통은 나에게 ___이다. 나는 고통을 ___하게 대한다’를 쓰고, 그 태도가 실제로 시험받았던 최근 사례를 덧붙이세요.',
    why: '고통에 대한 태도는 위기 전에 정해두어야 위기 때 작동합니다. 사례로 검증된 문장만이 실제 태도입니다.',
    cues: [
      '두 문장 → 그것이 스토아/불교/실존주의 중 어디에 가까운지 표시.',
      '최근 시험 사례에서 실제로 그렇게 대했나요? 아니라면 무엇이 방해했나요?',
      '다음 고통이 올 때 자신에게 할 첫 문장.',
    ],
    prereqIds: ['suf-second-arrow'],
    lensIds: ['frankl-logotherapy', 'stoicism-dichotomy', 'buddhism-dukkha', 'kross-self-distancing'],
    tags: ['고통', '종합', '태도'],
    minutes: 20,
  },

  // ───────────────────────────── 자유와 책임 ─────────────────────────────
  {
    id: 'free-felt',
    domainId: 'freedom',
    level: 1,
    kind: 'experience',
    title: '가장 자유롭다고 느낀 순간과 가장 갇혀 있다고 느낀 순간을 각각 떠올려보세요. 무엇이 있었고 무엇이 없었나요?',
    why: '자유의 감각은 정의보다 정확합니다. 두 순간의 차이가 당신이 원하는 자유의 종류를 말해줍니다.',
    cues: [
      '두 장면을 구체적으로: 장소, 사람, 시간, 몸의 느낌.',
      '자유로운 순간: 방해가 없었나요, 스스로 정한 것을 하고 있었나요?',
      '갇힌 순간: 외부의 제약이었나요, 내부의 요구였나요?',
    ],
    lensIds: ['berlin-two-liberties', 'sdt-needs', 'fromm-escape-from-freedom'],
    tags: ['자유', '경험', '제약', '자율'],
    minutes: 10,
  },
  {
    id: 'free-regret',
    domainId: 'freedom',
    level: 1,
    kind: 'experience',
    title: '한 것 중의 후회와 하지 않은 것 중의 후회를 하나씩 적어보세요. 어느 쪽이 더 오래 남나요?',
    why: '연구는 장기적으로 ‘하지 않은 것’의 후회가 더 크다고 말합니다. 후회의 패턴은 당신이 자유를 어떻게 쓰고 있는지를 보여줍니다.',
    cues: [
      '두 후회를 적고, 그때 무엇이 결정을 막았는지(두려움, 정보 부족, 타인) 적으세요.',
      '하지 않은 것의 후회에서 ‘아직 할 수 있는 것’은?',
      '후회를 줄이는 당신만의 결정 규칙을 만들어본다면?',
    ],
    lensIds: ['gilovich-regret', 'regrets-of-dying'],
    tags: ['자유', '후회', '결정', '행동'],
    minutes: 10,
  },
  {
    id: 'free-define',
    domainId: 'freedom',
    level: 2,
    kind: 'definition',
    title: '자유는 ‘방해 없음’인가요, ‘스스로 정한 법을 따름’인가요? 당신이 원하는 자유는 무엇으로부터의 자유이고 무엇을 향한 자유인가요?',
    why: '벌린의 소극적/적극적 자유, 프롬의 ‘~로부터의 자유/~를 향한 자유’ 구분은 ‘자유롭고 싶다’는 막연한 소망을 구체적 요구로 바꿉니다.',
    cues: [
      '벗어나고 싶은 것 세 가지, 향하고 싶은 것 세 가지.',
      '방해가 전부 사라진 상태를 상상해보세요. 그때 무엇을 하나요? 무엇도 하지 않게 되나요?',
      '스스로 정한 규칙을 따르는 것이 자유라면, 지금 당신의 규칙은 무엇인가요?',
    ],
    prereqIds: ['free-felt'],
    lensIds: ['berlin-two-liberties', 'kant-autonomy', 'fromm-escape-from-freedom'],
    tags: ['자유', '정의', '소극적', '적극적', '자율'],
    minutes: 15,
  },
  {
    id: 'free-second-order',
    domainId: 'freedom',
    level: 2,
    kind: 'definition',
    title: '당신이 원하는 것 중 ‘원하지 않았으면 하는 원함’이 있나요? (인정 욕구, 중독, 질투) 그 위에는 어떤 의지가 있나요?',
    why: '프랑크푸르트는 ‘원함에 대한 원함’(2차 욕구)이 인격과 자유의 핵심이라고 봅니다. 욕구를 다 채우는 것이 아니라 어떤 욕구를 승인할지 정하는 것이 자유입니다.',
    cues: [
      '1차 욕구를 열 개 적고, 각각 ‘이 욕구를 갖고 싶은가’를 표시하세요.',
      '승인하지 않는 욕구가 당신을 움직일 때 어떤 느낌인가요?',
      '승인한 욕구를 더 강하게 만드는 방법이 있나요?',
    ],
    lensIds: ['frankfurt-caring', 'spinoza-joy', 'buddhism-dukkha'],
    tags: ['자유', '욕구', '의지', '2차 욕구', '중독'],
    minutes: 15,
  },
  {
    id: 'free-responsible-for',
    domainId: 'freedom',
    level: 2,
    kind: 'definition',
    title: '당신은 무엇에 책임이 있나요? 성격, 감정, 과거의 선택, 타인의 감정… 어디까지가 당신의 것인가요?',
    why: '책임의 범위를 너무 넓히면 죄책감에, 너무 좁히면 무력감에 빠집니다. 경계를 그리는 것이 자유의 절반입니다.',
    cues: [
      '‘내 책임이다’라고 느끼는 것 열 개를 적고, 실제로 통제 가능한지 표시하세요.',
      '타인의 감정에 대한 책임은 어디까지인가요?',
      '책임을 지는 것과 자책하는 것의 차이는?',
    ],
    lensIds: ['sartre-existentialism', 'stoicism-dichotomy', 'moral-luck', 'locus-of-control'],
    tags: ['자유', '책임', '경계', '통제'],
    minutes: 15,
  },
  {
    id: 'free-luck',
    domainId: 'freedom',
    level: 3,
    kind: 'contrast',
    title: '당신 삶의 좋은 것 중 얼마나가 운(태어난 곳, 시대, 유전, 만남)인가요? 그 사실이 자부심과 책임감을 어떻게 바꾸나요?',
    why: '도덕적 운의 문제는 공로와 책임의 개념을 흔듭니다. 운의 몫을 정직하게 인정하면 오만도 자책도 줄어듭니다.',
    cues: [
      '당신의 성취 하나를 골라 운/노력의 비율을 적어보세요.',
      '같은 노력을 하고도 실패한 사람을 떠올려보세요. 차이는 무엇이었나요?',
      '운을 인정하면 성취의 기쁨이 줄어드나요, 감사가 늘어나나요?',
    ],
    lensIds: ['moral-luck', 'nussbaum-capabilities'],
    tags: ['자유', '운', '공로', '겸손', '책임'],
    minutes: 15,
  },
  {
    id: 'free-bad-faith',
    domainId: 'freedom',
    level: 3,
    kind: 'contrast',
    title: '‘어쩔 수 없었다’고 말했지만 사실 선택이었던 일이 있나요? 사르트르의 ‘자기기만’ 개념으로 다시 본다면?',
    why: '사르트르는 우리가 자유의 무게를 피하려고 ‘어쩔 수 없음’을 지어낸다고 봅니다. 불편하지만, 이 시선은 무력감을 선택권으로 바꿉니다.',
    cues: [
      '‘어쩔 수 없었다’고 말한 최근 사례 하나.',
      '그때 실제로 있었던 다른 선택지와 그것을 택하지 않은 이유.',
      '자유를 인정하면 무엇이 무거워지고 무엇이 가벼워지나요?',
    ],
    lensIds: ['sartre-existentialism', 'fromm-escape-from-freedom', 'kierkegaard-self'],
    tags: ['자유', '자기기만', '선택', '실존주의'],
    minutes: 15,
  },
  {
    id: 'free-wuwei',
    domainId: 'freedom',
    level: 3,
    kind: 'contrast',
    title: '애쓰지 않음(無爲)이 오히려 자유라는 도가의 관점은 당신의 ‘노력하는 삶’과 어떻게 충돌하나요?',
    why: '서구적 자유가 ‘의지의 관철’이라면 도가의 자유는 ‘억지 부리지 않음’입니다. 두 관점은 삶의 리듬을 전혀 다르게 만듭니다.',
    cues: [
      '억지로 밀어붙여 망친 일과, 흐름에 맡겨 풀린 일을 하나씩.',
      '무위가 게으름과 다른 점은 무엇인가요?',
      '당신 삶에서 무위를 적용할 영역과 적용하면 안 될 영역은?',
    ],
    lensIds: ['laozi-wuwei', 'zhuangzi-useless-tree', 'han-burnout-society'],
    tags: ['자유', '무위', '도가', '노력', '흐름'],
    minutes: 15,
  },
  {
    id: 'free-synthesis',
    domainId: 'freedom',
    level: 4,
    kind: 'synthesis',
    title: '‘나는 ___에 대해 자유롭고 ___에 대해 책임이 있다’를 선언하고, 이 원칙이 최근 결정 하나를 어떻게 바꾸었을지 적으세요.',
    why: '자유와 책임의 경계를 문장으로 고정하면 결정이 빨라지고 자책이 줄어듭니다.',
    cues: [
      '한 문장 → 최근 결정에 적용 → 달라지는 점.',
      '이 원칙이 가장 시험받을 상황은?',
      '이 원칙은 가치·의미에 대한 입장과 일관되나요?',
    ],
    prereqIds: ['free-define'],
    lensIds: ['sartre-existentialism', 'stoicism-dichotomy', 'frankfurt-caring'],
    tags: ['자유', '종합', '책임', '원칙'],
    minutes: 20,
  },

  // ───────────────────────────── 시간과 죽음 ─────────────────────────────
  {
    id: 'mort-first',
    domainId: 'mortality',
    level: 1,
    kind: 'experience',
    title: '죽음을 처음 실감한 경험은 언제였나요? 그때 삶에서 무엇이 갑자기 중요해지거나 사소해졌나요?',
    why: '죽음의 실감은 가치의 재배열을 일으킵니다. 그때 무엇이 남고 무엇이 떨어졌는지가 당신의 진짜 우선순위입니다.',
    cues: [
      '장면 하나: 누구의 죽음, 혹은 어떤 위기였나요?',
      '그 직후 며칠 동안 무엇을 하고 싶었나요? 무엇이 하찮아 보였나요?',
      '그 재배열은 얼마나 지속되었나요? 다시 돌아온 것은 무엇인가요?',
    ],
    caution: '최근의 상실이라면 천천히, 원하는 만큼만 쓰세요.',
    lensIds: ['heidegger-being-toward-death', 'yalom-existential-givens', 'terror-management-theory'],
    tags: ['죽음', '경험', '우선순위', '상실'],
    minutes: 10,
  },
  {
    id: 'mort-week',
    domainId: 'mortality',
    level: 1,
    kind: 'experience',
    title: '인생이 대략 4,000주라면 당신은 몇 주를 썼나요? 남은 주를 생각할 때 드는 첫 감정은 무엇인가요?',
    why: '80년은 약 4,170주입니다. 숫자로 보면 시간은 추상이 아니라 재고가 됩니다. 첫 감정(초조, 평온, 부정)이 당신의 시간관을 드러냅니다.',
    cues: [
      '나이 × 52를 계산해보세요. 남은 주는?',
      '첫 감정을 적고, 그 감정이 어떤 믿음에서 오는지 적으세요.',
      '남은 주 중 정말 ‘내 것’인 시간은 몇 %인가요?',
    ],
    lensIds: ['burkeman-four-thousand-weeks', 'seneca-shortness-of-life'],
    tags: ['시간', '유한성', '계산', '감정'],
    minutes: 10,
  },
  {
    id: 'mort-fear',
    domainId: 'mortality',
    level: 2,
    kind: 'definition',
    title: '죽음의 무엇이 두려운가요? 소멸, 고통, 미완, 남겨진 사람, 잊힘… 각각에 대한 답은 달라야 합니다.',
    why: '‘죽음이 두렵다’는 여러 두려움의 묶음입니다. 풀어서 보면 어떤 것은 철학으로, 어떤 것은 행동으로, 어떤 것은 관계로 답할 수 있습니다.',
    cues: [
      '두려움을 항목별로 나누고 각각의 크기를 매기세요.',
      '에피쿠로스의 논증(죽음이 있을 때 나는 없다)은 어느 항목에 답이 되나요?',
      '행동으로 줄일 수 있는 두려움(미완, 남겨진 사람)은 무엇인가요?',
    ],
    prereqIds: ['mort-first'],
    lensIds: ['epicurus-death-is-nothing', 'nagel-death', 'terror-management-theory'],
    tags: ['죽음', '두려움', '분석', '소멸'],
    minutes: 15,
  },
  {
    id: 'mort-eulogy',
    domainId: 'mortality',
    level: 2,
    kind: 'practice',
    title: '당신의 추도사를 가장 가까운 사람의 목소리로 써보세요. 어떤 사람으로 기억되고 싶나요?',
    why: '추도사는 이력서와 다른 가치를 드러냅니다. 기억되고 싶은 모습과 지금 사는 모습의 차이가 바로 조정할 지점입니다.',
    cues: [
      '그 사람의 말투로, 성취보다 성품과 관계를 중심으로.',
      '쓰고 나서: 지금의 삶이 이 추도사를 뒷받침하나요?',
      '추도사에 쓰이길 바라지만 아직 사실이 아닌 문장 하나는?',
    ],
    caution: '무거운 연습입니다. 원하지 않으면 건너뛰어도 됩니다.',
    lensIds: ['regrets-of-dying', 'tolstoy', 'mcadams-narrative-identity'],
    tags: ['죽음', '추도사', '기억', '가치', '연습'],
    minutes: 20,
  },
  {
    id: 'mort-immortal',
    domainId: 'mortality',
    level: 3,
    kind: 'thought-experiment',
    title: '영원히 산다면 삶은 더 의미 있어질까요, 무의미해질까요? 무엇이 삶을 ‘완결 가능한 것’으로 만드나요?',
    why: '윌리엄스는 영원한 삶이 결국 권태로 무너진다고 논증했습니다. 유한성이 의미의 조건이라면, 죽음은 적이 아니라 형식입니다.',
    cues: [
      '300년을 산다고 상상해보세요. 100년째에 무엇을 하고 있나요? 200년째는?',
      '지금 당신을 움직이는 욕구 중 영원 앞에서도 살아남을 것은?',
      '유한하기 때문에 소중한 것의 목록을 적어보세요.',
    ],
    lensIds: ['williams-makropulos', 'epicurus-death-is-nothing', 'setiya-telic-atelic'],
    tags: ['죽음', '불멸', '사고실험', '권태', '유한성'],
    minutes: 15,
  },
  {
    id: 'mort-nothing-to-us',
    domainId: 'mortality',
    level: 3,
    kind: 'contrast',
    title: '‘죽음은 우리에게 아무것도 아니다’(에피쿠로스)라는 논증을 반박하거나 옹호해보세요.',
    why: '가장 오래된 죽음의 위로이자 가장 논쟁적인 논증입니다. 네이글의 반론(박탈)까지 검토하면 당신의 죽음관이 논리적 뼈대를 갖게 됩니다.',
    cues: [
      '논증을 당신의 말로 다시 써보세요.',
      '태어나기 전의 무(無)가 두렵지 않다면, 죽은 뒤의 무는 왜 다른가요?(루크레티우스의 대칭 논증)',
      '네이글: 죽음은 좋은 것을 빼앗기 때문에 나쁘다. 동의하나요?',
    ],
    prereqIds: ['mort-fear'],
    lensIds: ['epicurus-death-is-nothing', 'nagel-death'],
    tags: ['죽음', '에피쿠로스', '논증', '박탈'],
    minutes: 20,
  },
  {
    id: 'mort-daily',
    domainId: 'mortality',
    level: 3,
    kind: 'practice',
    title: '‘아침에 죽음을 생각하라’는 권고를 일주일 실천해본다면 무엇이 달라질 것 같나요? (또는 실천한 뒤의 기록)',
    why: '메멘토 모리는 우울이 아니라 정리의 기술입니다. 스토아와 김영민의 권고를 실제로 시험해보면 관념이 습관으로 바뀝니다.',
    cues: [
      '실천 전 예상 → 실천 후 실제. (일주일 뒤에 다시 와서 이어 쓰세요)',
      '아침의 죽음 생각이 그날의 결정 하나를 바꾼 사례.',
      '‘삶의 잡음’으로 드러난 것은 무엇이었나요?',
    ],
    lensIds: ['kim-youngmin-death-morning', 'seneca-shortness-of-life', 'stoicism-dichotomy'],
    tags: ['죽음', '메멘토 모리', '실천', '습관'],
    minutes: 10,
  },
  {
    id: 'mort-legacy-vs-presence',
    domainId: 'mortality',
    level: 3,
    kind: 'contrast',
    title: '남기는 것(유산)과 지금 사는 것(현존) 중 무엇이 죽음 앞에서 더 큰 위로가 되나요? 그 답은 당신의 의미론과 일치하나요?',
    why: '공포 관리 이론은 우리가 상징적 불멸(유산, 명성, 자녀)로 죽음 불안을 달랜다고 말합니다. 그것이 당신의 동력이라면, 알고 쓰는 것과 모르고 끌려가는 것은 다릅니다.',
    cues: [
      '당신이 남기고 싶은 것 세 가지. 그것이 없다면 삶은 덜 의미 있나요?',
      '아무것도 남기지 못해도 충분히 산 하루가 있었나요?',
      '유산 욕구가 지금의 삶을 갉아먹는 지점은?',
    ],
    lensIds: ['terror-management-theory', 'arendt-vita-activa', 'buddhism-dukkha'],
    tags: ['죽음', '유산', '현존', '불멸', '의미'],
    minutes: 15,
  },
  {
    id: 'mort-synthesis',
    domainId: 'mortality',
    level: 4,
    kind: 'synthesis',
    title: '‘죽음은 나에게 ___이며, 그래서 나는 ___를 우선한다’를 쓰고, 당장 이번 달에 달라질 한 가지를 적으세요.',
    why: '죽음에 대한 입장은 모든 우선순위의 근거입니다. 이번 달의 변화 하나로 입장을 검증하세요.',
    cues: [
      '한 문장 → 이 문장이 행복·의미·관계의 입장과 일관되는지 확인.',
      '이번 달에 달라질 한 가지, 그리고 그것을 확인할 날짜.',
      '이 입장이 흔들릴 때 다시 읽을 문장 하나.',
    ],
    prereqIds: ['mort-fear'],
    lensIds: ['heidegger-being-toward-death', 'seneca-shortness-of-life', 'epicurus-death-is-nothing', 'burkeman-four-thousand-weeks'],
    tags: ['죽음', '종합', '우선순위'],
    minutes: 20,
  },
]

export const QUESTION_MAP: Record<string, Question> = Object.fromEntries(QUESTIONS.map((q) => [q.id, q]))

export function questionsOfDomain(domainId: string): Question[] {
  return QUESTIONS.filter((q) => q.domainId === domainId).sort((a, b) => a.level - b.level)
}

/** The three questions the app was built around; used for onboarding. */
export const STARTER_QUESTION_IDS = ['hap-moments', 'joy-lost-time', 'mean-felt']
